
package calculadora;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

public class Calculadora extends javax.swing.JFrame {

    ScriptEngineManager sem = new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("JavaScript");
            
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JLabel();
        txtOperacion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_igual = new javax.swing.JButton();
        btn_delete_ = new javax.swing.JButton();
        btn_porcentaje_ = new javax.swing.JButton();
        btn_multiplicacion_ = new javax.swing.JButton();
        btn_division_ = new javax.swing.JButton();
        btn_resta_ = new javax.swing.JButton();
        btn_suma_ = new javax.swing.JButton();
        btn_c_ = new javax.swing.JButton();
        btn_4_ = new javax.swing.JButton();
        btn_5_ = new javax.swing.JButton();
        btn_6_ = new javax.swing.JButton();
        btn_1_ = new javax.swing.JButton();
        btn_2_ = new javax.swing.JButton();
        btn_3_ = new javax.swing.JButton();
        btn_7_ = new javax.swing.JButton();
        btn_8_ = new javax.swing.JButton();
        btn_9_ = new javax.swing.JButton();
        btn_0_ = new javax.swing.JButton();
        btn_punto_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);
        setSize(new java.awt.Dimension(340, 340));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 39, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(0, 183, 136));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 310, 50));

        txtOperacion.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(0, 183, 136));
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 310, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 150));

        jPanel3.setBackground(new java.awt.Color(46, 57, 81));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_igual.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_igual.setForeground(new java.awt.Color(21, 39, 64));
        btn_igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3_dark.png"))); // NOI18N
        btn_igual.setText("=");
        btn_igual.setFocusPainted(false);
        btn_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_igual.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });
        jPanel3.add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 50, 50));

        btn_delete_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btn_delete_.setForeground(new java.awt.Color(0, 183, 136));
        btn_delete_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_dark.png"))); // NOI18N
        btn_delete_.setText("<-");
        btn_delete_.setFocusPainted(false);
        btn_delete_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_delete_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_delete_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3_pressed_dark.png"))); // NOI18N
        btn_delete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete_, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 50, 50));

        btn_porcentaje_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_porcentaje_.setForeground(new java.awt.Color(0, 183, 136));
        btn_porcentaje_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_dark.png"))); // NOI18N
        btn_porcentaje_.setText("%");
        btn_porcentaje_.setFocusPainted(false);
        btn_porcentaje_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_porcentaje_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_porcentaje_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3_pressed_dark.png"))); // NOI18N
        btn_porcentaje_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porcentaje_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_porcentaje_, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        btn_multiplicacion_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_multiplicacion_.setForeground(new java.awt.Color(0, 183, 136));
        btn_multiplicacion_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_dark.png"))); // NOI18N
        btn_multiplicacion_.setText("x");
        btn_multiplicacion_.setFocusPainted(false);
        btn_multiplicacion_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multiplicacion_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_multiplicacion_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3_pressed_dark.png"))); // NOI18N
        btn_multiplicacion_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicacion_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_multiplicacion_, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 50, 50));

        btn_division_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_division_.setForeground(new java.awt.Color(0, 183, 136));
        btn_division_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_dark.png"))); // NOI18N
        btn_division_.setText("/");
        btn_division_.setFocusPainted(false);
        btn_division_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_division_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_division_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3_pressed_dark.png"))); // NOI18N
        btn_division_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_division_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_division_, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 50, 50));

        btn_resta_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        btn_resta_.setForeground(new java.awt.Color(0, 183, 136));
        btn_resta_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_dark.png"))); // NOI18N
        btn_resta_.setText("-");
        btn_resta_.setFocusPainted(false);
        btn_resta_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_resta_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_resta_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3_pressed_dark.png"))); // NOI18N
        btn_resta_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resta_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_resta_, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 50, 50));

        btn_suma_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_suma_.setForeground(new java.awt.Color(0, 183, 136));
        btn_suma_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_dark.png"))); // NOI18N
        btn_suma_.setText("+");
        btn_suma_.setFocusPainted(false);
        btn_suma_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_suma_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_suma_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3_pressed_dark.png"))); // NOI18N
        btn_suma_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suma_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_suma_, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, 50));

        btn_c_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_c_.setForeground(new java.awt.Color(0, 183, 136));
        btn_c_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_dark.png"))); // NOI18N
        btn_c_.setText("C");
        btn_c_.setFocusPainted(false);
        btn_c_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_c_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_c_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3_pressed_dark.png"))); // NOI18N
        btn_c_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_c_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        btn_4_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_4_.setForeground(new java.awt.Color(0, 183, 136));
        btn_4_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_4_.setText("4");
        btn_4_.setFocusPainted(false);
        btn_4_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_4_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_4_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_4_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_4_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 50));

        btn_5_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_5_.setForeground(new java.awt.Color(0, 183, 136));
        btn_5_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_5_.setText("5");
        btn_5_.setFocusPainted(false);
        btn_5_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_5_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_5_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_5_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_5_, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 50, 50));

        btn_6_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_6_.setForeground(new java.awt.Color(0, 183, 136));
        btn_6_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_6_.setText("6");
        btn_6_.setFocusPainted(false);
        btn_6_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_6_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_6_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_6_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_6_, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 50, 50));

        btn_1_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_1_.setForeground(new java.awt.Color(0, 183, 136));
        btn_1_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_1_.setText("1");
        btn_1_.setFocusPainted(false);
        btn_1_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_1_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_1_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_1_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 50));

        btn_2_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_2_.setForeground(new java.awt.Color(0, 183, 136));
        btn_2_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_2_.setText("2");
        btn_2_.setFocusPainted(false);
        btn_2_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_2_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_2_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 50, 50));

        btn_3_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_3_.setForeground(new java.awt.Color(0, 183, 136));
        btn_3_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_3_.setText("3");
        btn_3_.setFocusPainted(false);
        btn_3_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_3_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_3_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_3_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_3_, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 50, 50));

        btn_7_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_7_.setForeground(new java.awt.Color(0, 183, 136));
        btn_7_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_7_.setText("7");
        btn_7_.setFocusPainted(false);
        btn_7_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_7_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_7_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_7_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_7_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 50));

        btn_8_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_8_.setForeground(new java.awt.Color(0, 183, 136));
        btn_8_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_8_.setText("8");
        btn_8_.setFocusPainted(false);
        btn_8_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_8_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_8_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_8_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_8_, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 50));

        btn_9_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_9_.setForeground(new java.awt.Color(0, 183, 136));
        btn_9_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_9_.setText("9");
        btn_9_.setFocusPainted(false);
        btn_9_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_9_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_9_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_9_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_9_, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 50, 50));

        btn_0_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_0_.setForeground(new java.awt.Color(0, 183, 136));
        btn_0_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_0_.setText("0");
        btn_0_.setFocusPainted(false);
        btn_0_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_0_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_0_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_0_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_0_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 50));

        btn_punto_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btn_punto_.setForeground(new java.awt.Color(0, 183, 136));
        btn_punto_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_punto_.setText(".");
        btn_punto_.setFocusPainted(false);
        btn_punto_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_punto_.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_punto_.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_dark.png"))); // NOI18N
        btn_punto_.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed_dark.png"))); // NOI18N
        btn_punto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_punto_ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_punto_, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 50, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_porcentaje_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porcentaje_ActionPerformed
        addNumero("%");
    }//GEN-LAST:event_btn_porcentaje_ActionPerformed

    private void btn_9_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9_ActionPerformed
        addNumero("9");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_9_ActionPerformed

    private void btn_8_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8_ActionPerformed
        addNumero("8");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_8_ActionPerformed

    private void btn_5_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5_ActionPerformed
        addNumero("5");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_5_ActionPerformed

    private void btn_6_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6_ActionPerformed
        addNumero("6");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_6_ActionPerformed

    private void btn_2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2_ActionPerformed
        addNumero("2");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_2_ActionPerformed

    private void btn_3_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3_ActionPerformed
        addNumero("3");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_3_ActionPerformed

    private void btn_punto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_punto_ActionPerformed
        addNumero(".");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_punto_ActionPerformed

    private void btn_c_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c_ActionPerformed
        txtOperacion.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_btn_c_ActionPerformed

    private void btn_1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1_ActionPerformed
        addNumero("1");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_1_ActionPerformed

    private void btn_0_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0_ActionPerformed
        addNumero("0");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_0_ActionPerformed

    private void btn_4_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4_ActionPerformed
       addNumero("4");
       btn_igual.doClick();
    }//GEN-LAST:event_btn_4_ActionPerformed

    private void btn_7_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7_ActionPerformed
        addNumero("7");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_7_ActionPerformed

    private void btn_division_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_division_ActionPerformed
        addNumero("/");
    }//GEN-LAST:event_btn_division_ActionPerformed

    private void btn_multiplicacion_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicacion_ActionPerformed
        addNumero("*");
    }//GEN-LAST:event_btn_multiplicacion_ActionPerformed

    private void btn_resta_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resta_ActionPerformed
        addNumero("-");
    }//GEN-LAST:event_btn_resta_ActionPerformed

    private void btn_suma_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suma_ActionPerformed
        addNumero("+");
    }//GEN-LAST:event_btn_suma_ActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        try{
            String res =  se.eval(txtOperacion.getText()).toString();
            txtResultado.setText(res);
        }   catch(Exception e){
            txtOperacion.setText("Error");
        }
        
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_ActionPerformed
        String texto = txtOperacion.getText().substring(0,txtOperacion.getText().length() - 1);
        txtOperacion.setText(texto);
        txtResultado.setText(texto);
    }//GEN-LAST:event_btn_delete_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    
    public void addNumero(String digito){
        txtOperacion.setText(txtOperacion.getText() + digito);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0_;
    private javax.swing.JButton btn_1_;
    private javax.swing.JButton btn_2_;
    private javax.swing.JButton btn_3_;
    private javax.swing.JButton btn_4_;
    private javax.swing.JButton btn_5_;
    private javax.swing.JButton btn_6_;
    private javax.swing.JButton btn_7_;
    private javax.swing.JButton btn_8_;
    private javax.swing.JButton btn_9_;
    private javax.swing.JButton btn_c_;
    private javax.swing.JButton btn_delete_;
    private javax.swing.JButton btn_division_;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multiplicacion_;
    private javax.swing.JButton btn_porcentaje_;
    private javax.swing.JButton btn_punto_;
    private javax.swing.JButton btn_resta_;
    private javax.swing.JButton btn_suma_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
